name: "Linting stage"

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened]

jobs:
  set-up-dependencies:
    name: "Set up dependencies"
    runs-on: ubuntu-latest
    steps:
      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

  linting:
    name: "linting"
    needs: set-up-dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: |
          pip install pipenv
          pipenv install --dev --system

      - name: "Lint Python files:"
        run: |
          ./lint.sh
